import { AmpAgent } from "../../../src/agents/AmpAgent";
import * as FileSystemUtils from "../../../src/core/FileSystemUtils";
import { revertAllAgentConfigs } from "../../../src/revert";
import * as fs from "fs/promises";
import * as path from "path";
import * as os from "os";

// Only mock FileSystemUtils for unit tests, not integration tests
jest.mock("../../../src/core/FileSystemUtils", () => {
	const actual = jest.requireActual("../../../src/core/FileSystemUtils");
	return {
		...actual,
		writeGeneratedFile: jest.fn(),
		backupFile: jest.fn(),
	};
});

describe("AmpAgent", () => {
	let agent: AmpAgent;

	beforeEach(() => {
		agent = new AmpAgent();
		(FileSystemUtils.writeGeneratedFile as jest.Mock).mockClear();
	});

	it("should return the correct identifier", () => {
		expect(agent.getIdentifier()).toBe("amp");
	});

	it("should return the correct name", () => {
		expect(agent.getName()).toBe("Amp");
	});

	it("should return empty MCP server key (no MCP propagation)", () => {
		expect(agent.getMcpServerKey()).toBe("");
	});

	it("should return the correct default output path", () => {
		const base = path.join(os.tmpdir(), "amp-agent-path-test");
		expect(agent.getDefaultOutputPath(base)).toBe(path.join(base, "AGENTS.md"));
	});

	it("should apply skiller config to the default output path", async () => {
		const backupFile = jest.spyOn(FileSystemUtils, "backupFile");
		const writeGeneratedFile = jest.spyOn(
			FileSystemUtils,
			"writeGeneratedFile",
		);
		const base = await fs.mkdtemp(path.join(os.tmpdir(), "amp-agent-default-"));
		await agent.applySkillerConfig("rules", base, null);
		const expected = path.join(base, "AGENTS.md");
		expect(backupFile).toHaveBeenCalledWith(expected);
		expect(writeGeneratedFile).toHaveBeenCalledWith(
			expected,
			"<!-- Generated by Skiller -->\nrules",
		);
	});

	it("should apply skiller config to a custom output path", async () => {
		const backupFile = jest.spyOn(FileSystemUtils, "backupFile");
		const writeGeneratedFile = jest.spyOn(
			FileSystemUtils,
			"writeGeneratedFile",
		);
		const base = await fs.mkdtemp(path.join(os.tmpdir(), "amp-agent-custom-"));
		await agent.applySkillerConfig("rules", base, null, {
			outputPath: "CUSTOM.md",
		});
		const expected = path.join(base, "CUSTOM.md");
		expect(backupFile).toHaveBeenCalledWith(expected);
		expect(writeGeneratedFile).toHaveBeenCalledWith(
			expected,
			"<!-- Generated by Skiller -->\nrules",
		);
	});

	describe("integration with backup and revert functionality", () => {
		let tmpDir: string;
		let realAgent: AmpAgent;
		let originalWriteGeneratedFile: any;

		beforeEach(async () => {
			// Restore the real writeGeneratedFile implementation for integration tests
			originalWriteGeneratedFile = jest.requireActual(
				"../../../src/core/FileSystemUtils",
			).writeGeneratedFile;
			(FileSystemUtils.writeGeneratedFile as jest.Mock).mockImplementation(
				originalWriteGeneratedFile,
			);

			tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "amp-agent-test-"));
			realAgent = new AmpAgent();

			// Create .claude directory for revert functionality
			const skillerDir = path.join(tmpDir, ".claude");
			await fs.mkdir(skillerDir, { recursive: true });
			// Create skiller.toml to make it a valid skiller directory
			await fs.writeFile(path.join(skillerDir, "skiller.toml"), "");
			await fs.writeFile(path.join(skillerDir, "AGENTS.md"), "Test rules");
		});

		afterEach(async () => {
			await fs.rm(tmpDir, { recursive: true, force: true });
			// Restore the mock for unit tests
			(FileSystemUtils.writeGeneratedFile as jest.Mock).mockReset();
		});

		it("should create AGENTS.md file when applying skiller config", async () => {
			const rules = "Amp agent rules";
			await realAgent.applySkillerConfig(rules, tmpDir, null);

			const agentPath = path.join(tmpDir, "AGENTS.md");
			const content = await fs.readFile(agentPath, "utf8");
			expect(content).toBe(`<!-- Generated by Skiller -->\n${rules}`);
		});

		it("should create backup when overwriting existing AGENTS.md file", async () => {
			const agentPath = path.join(tmpDir, "AGENTS.md");
			const originalContent = "Original content";
			const newContent = "New rules";

			// Create original file
			await fs.writeFile(agentPath, originalContent);

			// Apply new rules (AmpAgent itself doesn't create backups, that's handled by the apply-engine)
			await realAgent.applySkillerConfig(newContent, tmpDir, null);

			// Verify new content is written
			const content = await fs.readFile(agentPath, "utf8");
			expect(content).toBe(`<!-- Generated by Skiller -->\n${newContent}`);
		});

		it("should be properly reverted by revertAllAgentConfigs", async () => {
			const rules = "Amp agent rules";
			await realAgent.applySkillerConfig(rules, tmpDir, null);

			const agentPath = path.join(tmpDir, "AGENTS.md");

			// Verify file exists
			await expect(fs.access(agentPath)).resolves.toBeUndefined();

			// Revert amp agent
			await revertAllAgentConfigs(
				tmpDir,
				["amp"],
				undefined,
				false,
				false,
				false,
			);

			// Verify file is removed
			await expect(fs.access(agentPath)).rejects.toThrow();
		});

		it("should restore from backup when revert is called", async () => {
			const agentPath = path.join(tmpDir, "AGENTS.md");
			const backupPath = `${agentPath}.bak`;
			const originalContent = "Original Amp content";
			const newContent = "New Amp rules";

			// Create original file and backup
			await fs.writeFile(agentPath, originalContent);
			await fs.writeFile(backupPath, originalContent);

			// Overwrite with new content (simulating skiller apply)
			await fs.writeFile(agentPath, newContent);

			// Verify new content is in place
			expect(await fs.readFile(agentPath, "utf8")).toBe(newContent);

			// Revert
			await revertAllAgentConfigs(
				tmpDir,
				["amp"],
				undefined,
				false,
				false,
				false,
			);

			// Verify original content is restored
			const restoredContent = await fs.readFile(agentPath, "utf8");
			expect(restoredContent).toBe(originalContent);

			// Verify backup is cleaned up (default behavior)
			await expect(fs.access(backupPath)).rejects.toThrow();
		});

		it("should handle custom output path correctly", async () => {
			const customPath = "custom-amp.md";
			const rules = "Custom rules";

			await realAgent.applySkillerConfig(rules, tmpDir, null, {
				outputPath: customPath,
			});

			const customFilePath = path.join(tmpDir, customPath);
			const content = await fs.readFile(customFilePath, "utf8");
			expect(content).toBe(`<!-- Generated by Skiller -->\n${rules}`);
		});

		it("should skip rewrite when content is unchanged (idempotent behavior)", async () => {
			const rules = "Stable content for idempotent test";

			// First application
			await realAgent.applySkillerConfig(rules, tmpDir, null);
			const agentPath = path.join(tmpDir, "AGENTS.md");
			const statBefore = await fs.stat(agentPath);

			// Wait a bit to ensure mtime would differ if file was rewritten
			await new Promise((resolve) => setTimeout(resolve, 10));

			// Second application with same content
			await realAgent.applySkillerConfig(rules, tmpDir, null);
			const statAfter = await fs.stat(agentPath);

			// mtime should be unchanged because write was skipped
			expect(statAfter.mtimeMs).toBe(statBefore.mtimeMs);
		});

		it("should support native skills", () => {
			const agent = new AmpAgent();
			expect(agent.supportsNativeSkills?.()).toBe(true);
		});

		it("should return .agents/skills path (shared with Goose)", () => {
			const agent = new AmpAgent();
			const projectRoot = "/test/project";
			expect(agent.getSkillsPath?.(projectRoot)).toBe("/test/project/.agents/skills");
		});
	});
});
