import { WindsurfAgent } from '../../../src/agents/WindsurfAgent';
import * as FileSystemUtils from '../../../src/core/FileSystemUtils';

jest.mock('../../../src/core/FileSystemUtils');

describe('WindsurfAgent', () => {
  let agent: WindsurfAgent;

  beforeEach(() => {
    agent = new WindsurfAgent();
    jest.clearAllMocks();
  });

  it('should return the correct identifier', () => {
    expect(agent.getIdentifier()).toBe('windsurf');
  });

  it('should return the correct name', () => {
    expect(agent.getName()).toBe('Windsurf');
  });

  it('should return the correct default output path', () => {
    expect(agent.getDefaultOutputPath('/root')).toBe('/root/AGENTS.md');
  });

  it('should apply skiller config to the default output path', async () => {
    const writeGeneratedFile = jest.spyOn(
      FileSystemUtils,
      'writeGeneratedFile',
    );
    await agent.applySkillerConfig('rules', '/root', null);
    expect(writeGeneratedFile).toHaveBeenCalledWith(
      '/root/AGENTS.md',
      '<!-- Generated by Skiller -->\nrules',
    );
  });

  it('should apply skiller config to a custom output path', async () => {
    const writeGeneratedFile = jest.spyOn(
      FileSystemUtils,
      'writeGeneratedFile',
    );
    await agent.applySkillerConfig('rules', '/root', null, {
      outputPath: 'CUSTOM.md',
    });
    expect(writeGeneratedFile).toHaveBeenCalledWith(
      '/root/CUSTOM.md',
      '<!-- Generated by Skiller -->\nrules',
    );
  });

  it('should support native skills', () => {
    expect(agent.supportsNativeSkills?.()).toBe(true);
  });

  it('should return .windsurf/skills path', () => {
    expect(agent.getSkillsPath?.('/test/project')).toBe(
      '/test/project/.windsurf/skills',
    );
  });
});
